### ISSUE TITLE
Tests failing due to browserify/esprima error

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pouchdb-replication-stream#8]
wtf?

```
> pouchdb-replication-stream@0.1.0 dev /Users/nolan/workspace/pouchdb-replication-stream
> browserify test/test.js > test/test-bundle.js && npm run dev-server


/Users/nolan/workspace/pouchdb-replication-stream/node_modules/es3ify/node_modules/jstransform/src/jstransform.js:222
    throw e;
          ^
Error: Parse Error: Line 2: Unexpected token :
    at throwError (/Users/nolan/workspace/pouchdb-replication-stream/node_modules/es3ify/node_modules/esprima-fb/esprima.js:2154:21)
    at throwUnexpected (/Users/nolan/workspace/pouchdb-replication-stream/node_modules/es3ify/node_modules/esprima-fb/esprima.js:2216:9)
    at consumeSemicolon (/Users/nolan/workspace/pouchdb-replication-stream/node_modules/es3ify/node_modules/esprima-fb/esprima.js:2302:13)
    at parseStatement (/Users/nolan/workspace/pouchdb-replication-stream/node_modules/es3ify/node_modules/esprima-fb/esprima.js:4150:9)
    at /Users/nolan/workspace/pouchdb-replication-stream/node_modules/es3ify/node_modules/esprima-fb/esprima.js:5832:38
    at parseSourceElement (/Users/nolan/workspace/pouchdb-replication-stream/node_modules/es3ify/node_modules/esprima-fb/esprima.js:4682:20)
    at parseStatementList (/Users/nolan/workspace/pouchdb-replication-stream/node_modules/es3ify/node_modules/esprima-fb/esprima.js:3274:25)
    at parseBlock (/Users/nolan/workspace/pouchdb-replication-stream/node_modules/es3ify/node_modules/esprima-fb/esprima.js:3289:17)
    at /Users/nolan/workspace/pouchdb-replication-stream/node_modules/es3ify/node_modules/esprima-fb/esprima.js:5832:38
    at parseStatement (/Users/nolan/workspace/pouchdb-replication-stream/node_modules/es3ify/node_modules/esprima-fb/esprima.js:4088:24)
```

**Comment by nolanlawson** [comment]
This has been fixed last I checked.
